spring:
  application:
    name: todolist-task-distributor

kafka:
  consumer:
    bootstrapServers: localhost:29092
    groupId: todolist-task-distributor
    autoOffsetReset: latest
    maxPollIntervalMs: 300_000
    enableAutoCommit: false
    concurrency: 1
    schemaRegistryUrl: 'http://localhost:28081'

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8081